[project]
name = "word-guesser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
    "qdrant-client>=1.14.2",
    "tqdm>=4.67.1",
]
